### ISSUE TITLE
chrome extension

### ISSUE THREAD

**Issue by NeverBeLazyG** [KingDanx/edge-tts-electron#2]
please make a chrome extension, which can read the actual website

**Comment by herbitahir** [comment]
[Reading the Autal Website.zip](https://github.com/user-attachments/files/17686346/Reading.the.Autal.Website.zip)

**Comment by NeverBeLazyG** [comment]
First of all, thank you very much my friend. I have installed the extension, but unfortunately it does not work. What do I need to pay attention to? Are there any prerequisites that need to be met for it to work?
![image](https://github.com/user-attachments/assets/ca89684a-7b19-4618-ad60-998480bf39c2)

**Comment by KingDanx** [comment]
I'm not going to be making a chrome extension based off this application.   I really only made the application as a favor for a friend and I'm also not sure how I could get python to even work in a chrome extension.

**Comment by NeverBeLazyG** [comment]
> I'm not going to be making a chrome extension based off this application. I really only made the application as a favor for a friend and I'm also not sure how I could get python to even work in a chrome extension.

i asked the other guy, who mad the chrome extenstion not oyu..

**Comment by herbitahir** [comment]
Friend, i tried... but i am busy.... but i will back to you... Soon and will solve the problem... as soon as possible
